### PR TITLE
Challenge intro page layout and start translations

### LINKED ISSUE #132: Layout issue on Challenge Intro page for Desktop & Mobile view
**Describe the bug**
The layout for the challenge introduction page is different from figma mockup - https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=83%3A2379&t=d9uHpsXOJhhxBAMy-0

**To Reproduce**

1. Go to https://savingsatoshi.com/chapters/chapter-1/transacting
2. See the error

**Screenshots and/or logs**
Screenshot 2023-02-04 at 1 24 02 PM
Screenshot 2023-02-04 at 1 23 35 PM

### PR DESCRIPTION
**Pull request by benalleng**
Closes #132. Matches the tile page to figma in mobile view

[Challenge Intro](https://saving-satoshi-git-fork-benalleng-transac-c7393e-saving-satoshi.vercel.app/en/chapters/chapter-1/transacting-1)

## Pull Request checklist

Please review the below PR requirements:

- Build was run locally and any changes were pushed
- Ensure that the title clearly describes the changes
- Issue to be referenced in the PR description rather than in the commits or PR title
- Clean commit history

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Tested this. Desktop looks great!
Screenshot 2023-02-06 at 10 12 19 AM

However there is one discrepancy for mobile view. The continue button in figma (on the left) seems to be full screen but the version in the PR (on the right) is not.
Screenshot 2023-02-06 at 10 16 26 AM

**Comment by ecurrencyhodler** [comment]
tACK! Thanks for the quick fix. 
Screenshot 2023-02-06 at 11 20 13 AM

**Comment by vinayaksh42** [comment]
Hey @benalleng, I was actually thinking to create the `Challenge Intro` into a template as suggested in this notion document - https://www.notion.so/Lesson-templates-e2b3e895c3f3431daa76f2fcb30fac7e. It will be great to have a re-usable component for easily creating challenge introductions.

**Comment by vinayaksh42** [comment]
That sounds great! @benalleng, I think you can finish up the template work within this PR.

**Comment by benalleng** [comment]
@vinayaksh42 Just wanted to check in with some clarification as to how you might want the templates to be formatted. I know you had A file somewhere for templates but i can't seem to find where it went :sweat_smile: if you could link me to it or maybe we could make a bit more of a more precise template format moving forward.

File: ui/chapter/Intro.tsx [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  })
+
+  return (
+    <div className="grid w-full grid-cols-1 justify-center justify-items-center">
+      <div className="flex w-full items-center px-6 text-white lg:w-1/2 lg:px-0">
+        <div className="content-center justify-items-center px-1 font-nunito">
+          <div className="genesis">
+            <Title>{title}</Title>
+            {textRender}
+          </div>
```
Comment (benalleng) [inline ui/chapter/Intro.tsx:23]: Seeing the other templates they left a lot more variability to the developer how each page would be formatted, I wonder whether or not we should continue to just pass children props like in other templates or is it ok to have this template be so narrowly coded like this.

**Comment by vinayaksh42** [comment]
> @vinayaksh42 Just wanted to check in with some clarification as to how you might want the templates to be formatted. I know you had A file somewhere for templates but i can't seem to find where it went 😅 if you could link me to it or maybe we could make a bit more of a more precise template format moving forward.

Here is the notion file for the lesson templates - https://www.notion.so/Lesson-templates-e2b3e895c3f3431daa76f2fcb30fac7e

File: ui/chapter/Intro.tsx (hunk 1 above)
Comment (vinayaksh42) [reply ui/chapter/Intro.tsx]: I'm unsure which approach is superior, but it's worth noting that developers may require some flexibility in content types for different lesson introductions. For instance, one introduction might require an image, while another may need something else. To address this, passing down children props could be a more effective way to provide the necessary content. Within the template, we can define the fundamental structure of the page so that all lesson introductions adhere to a standard set of styling rules.

File: ui/chapter/Intro.tsx [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    )
+  })
+
+  return (
+    <div className="my-auto grid w-full grid-cols-1 justify-center justify-items-center">
+      <div className="flex w-full items-center px-6 text-white lg:w-1/2 lg:px-0">
+        <div className="content-center justify-items-center px-1 font-nunito">
+          <div className="genesis">
+            <Title>{title}</Title>
+            {textRender}
```
Comment (afterburn) [inline ui/chapter/Intro.tsx:26]: Let's just do these inline unless we have a very specific reason for moving them out of the jsx, e.g. if you want to execute some logic for each of the children.

File: content/lessons/transacting/transacting-1/index.tsx [hunk 3]
```diff
@@ -1,41 +1,36 @@
...
-              against other miners for the privilege of building on the chain.
-            </Text>
-
-            <Text className="pt-2 text-lg">
-              Transactions have two parts: inputs and outputs. In the previous
-              exercise we decoded a secret message found inside a transaction
-              input. This time we’ll decode a message that belongs to the output
-              part.
-            </Text>
+  const text = [
```
Comment (afterburn) [inline content/lessons/transacting/transacting-1/index.tsx:6]: Hmm I'm not sure I like this approach, I think I would prefer just using children in this case. I noticed the conversation you guys had about flexibility and I think it's perfectly fine to use `children` instead of this json approach. So:

```jsx
<Intro
  title={}
  next={}
>
  <p class="pt-2 text-lg">...</p>
  <p class="pt-2 text-lg">...</p>
  <p class="pt-2 text-lg">...</p>
</Intro>
```

Then in Intro.tsx:
```jsx
<div className="genesis">
  <Title>{title}</Title>
  {children}
</div>
```

That way I can deviate from simple `<p>` tags with some css class more easily as a contributor.

**Review by afterburn — CHANGES_REQUESTED** [review]
Thank you both @benalleng for the work and @vinayaksh42 for reviewing this. I did leave some minor comments.

**Review by vinayaksh42 — APPROVED** [review]
great work @benalleng, all the changes LGTM!

**Comment by ecurrencyhodler** [comment]
Hey ben looks like 1 requested change still needs to be resolved.

**Comment by benalleng** [comment]
Hmm can't see any changes to resolve, maybe @afterburn needs to do a re-review?

**Review by afterburn — CHANGES_REQUESTED** [review]
Left a nitpicky comment but afterwards we're good to merge

**Review by afterburn — APPROVED** [review]
