### PR TITLE
Save data key for CH8BBK8

### LINKED ISSUE #1120: Chapter 8 building blocks 8 code saved to wrong lesson key
`CH8BBK8` is saved to `CH6PUT1`

```
  const getPrevLessonData = async () => {
    const data = await getData('CH8BBK7')

    if (data) {
      setPrevData({
        lesson_id: `CH6PUT1_${completedChapter6?.level.toString()}`,
        data: data?.code?.getDecoded(),
      })
    }
  }
```

### PR DESCRIPTION
**Pull request by benalleng**
Closes #1120

### CODE REVIEW

File: content/lessons/chapter-8/building-blocks-8.tsx [hunk 1]
```diff
@@ -41,7 +41,7 @@ export default function BuildingBlocks8({ lang }) {
 
     if (data) {
       setPrevData({
-        lesson_id: `CH6PUT1_${completedChapter6?.level.toString()}`,
+        lesson_id: `CH8BBK7`,
```
Comment (satsie) [inline content/lessons/chapter-8/building-blocks-8.tsx:44]: oh my word! Good catch!
