### PR TITLE
Fix for missing translation on Done page

### LINKED ISSUE #150: Chapter 1 completion page displays wrong title
**Describe the bug**
Chapter 1 completion page shows `done.title` instead of `you did it!!!` - [figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=99%3A3790&t=bBpI4U7sHiLwdqcT-0)

**To Reproduce**

1. Go to https://savingsatoshi.com/en/chapters/chapter-1/done
2. See the error

**Screenshots and/or logs**
Screenshot 2023-02-14 at 8 29 15 PM

### PR DESCRIPTION
**Pull request by afterburn**
## Summary
This PR fixes #150.

Please review the below PR requirements:

- [x] Build was run locally and any changes were pushed
- [x] Ensure that the title clearly describes the changes
- [x] Issue to be referenced in the PR description rather than in the commits or PR title
- [x] Clean commit history

### CODE REVIEW

**Comment by afterburn** [comment]
Doesn't seem to fix #149 unfortunately, I'll remove the changes I've made for that particular part so we use this PR for #150 and address #149 in a separate PR.

**Comment by ecurrencyhodler** [comment]
Hey Kevin! Let me try to get another contributor involved with reviewing. If not, I'll take a look in the next couple of days.

**Review by vinayaksh42 — APPROVED** [review]
LGTM! the [preview](https://saving-satoshi-git-fix-149-150-saving-satoshi.vercel.app/en/chapters/chapter-1/done) looks the same as[ figma mockup ](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=99%3A3790&t=zv5Qcv4nYqOKgNjC-0)

File: content/lessons/done/translations.ts [hunk 1]
```diff
@@ -2,10 +2,14 @@ export const translations = {
   done: {
     en: {
       title: 'Done',
```
Comment (shaavan) [inline content/lessons/done/translations.ts:4]: Since we are fixing the way the title is displayed. Let's also update the text displayed to match the Figma file.
```suggestion
      title: 'You did it!!!',
```

File: content/lessons/done/translations.ts [hunk 2]
```diff
@@ -2,10 +2,14 @@ export const translations = {
...
+      description:
+        'Amazing. You completed the first chapter and learned a lot about hashes and transactions. Are you ready for more?',
     },
 
     nl: {
       title: 'Einde',
```
Comment (shaavan) [inline content/lessons/done/translations.ts:10]: Also here.

```suggestion
      title: 'Je hebt het gedaan!!!',
```

**Review by shaavan — COMMENTED** [review]
Thanks for taking this up, @afterburn!
