### PR TITLE
Terminal UI component

### LINKED ISSUE #165: Add command history to Terminal
**Describe the enhancement**
It'd be nice if I would be able to use my up/down arrow keys to navigate between commands I previously entered in the `Terminal` component. This is a very natural thing to be doing if you're a terminal user, and can prevent some frustration if you make a typo and have to type the command from the start.

**Suggested solution**
I don't suggest we persist these across sessions. We should just keep track of any commands users input in the Terminal component itself via its state.

### LINKED ISSUE #187: Disable spellcheck and autocomplete on terminal input field
While testing on mobile, iOS tried to auto-correct my code input, which of course made no sense. We can disable this via the [spellcheck](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) and [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attributes.

### LINKED ISSUE #188: Paste is not working on iOS mobile
**Describe the bug**
I copied the values for challenge 1. I went to the code section to paste it but the paste option did not appear. Also when I click "paste" the screen refreshed or flashes for some reason.

**To Reproduce**

1. Go to challenge 1 and copy the terminal input
2. Go to "code" and try to copy paste
3. The ability to paste doesn't appear.

**Expected behavior**
Option to paste text should appear.

**Screenshots and/or logs**

https://user-images.githubusercontent.com/32662508/220992645-7f976f00-e65d-4c69-8068-f471d984adb3.MP4

### LINKED ISSUE #202: Letters "fi" when entered into terminal get smashed together.
**Describe the bug**
Letters "fi" when entered into terminal get smashed together.

Screenshot 2023-02-26 at 8 58 36 AM

### LINKED ISSUE #205: Stop collecting input as an answer once challenge is completed.
If a user completes a challenges, continues to play around in terminal, and enters a command that is NOT the answer, they are prevented from moving forward.

Allow a user to continue to the next chapter once they get the correct answer even after they continue playing around in the terminal

### LINKED ISSUE #207: Blur input to hide keyboard on mobile after challenge has been completed
Based on this convo https://github.com/saving-satoshi/saving-satoshi/pull/201#issuecomment-1445387220

"I implemented the input simply losing focus on a completed challenge so that the keyboard disappears. At the moment once you complete a challenge it's hard to tell what to do next. Especially at this early stage where there isn't a lot of muscle memory for challenges."
221419562-00d29582-0f6e-4bb1-afca-28adff16caf9

The problem is that it's unclear to the user what to do next on mobile as the "next" button is hidden.

The proposal here that we discussed was to blur the input so that the keyboard fades away on mobile after challenge has been completed.

### PR DESCRIPTION
**Pull request by vinayaksh42**
Fixes #188, Fixes #187, Fixes #165, Fixes #202, Fixes #205, and Fixes #207

[Preview link](https://saving-satoshi-git-fork-vinayaksh42-issue187-savingsatoshi.vercel.app/en/chapters/chapter-1/genesis-2)

changes:
1.  Disabled spell check and autocomplete for the terminal input area
2. paste now works in safari (iPhone)
3. Added command history option (use up and down arrow keys to cycle through previous commands)

A few changes that can be added:
1. disabling input when the challenge is completed (not sure if we should implement this change)
2. #145 - the [figma mockup](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1604%3A21036&t=aJplYJ7JVCvKwVOt-0) however has a normal terminal caret

Current known bugs:
1. terminal interface height not spanning over the entire div
3. Smooth Scroll behavior when the div expands

### CODE REVIEW

**Comment by benalleng** [comment]
tACK on Firefox mobile

I implemented the input simply losing focus on a completed challenge so that the keyboard disappears. At the moment once you complete a challenge it's hard to tell what to do next. Especially at this early stage.
Screenshot_20230226-101710

**Comment by ecurrencyhodler** [comment]
Hey Ben. Good catch. The success text is currently being revamped in https://github.com/saving-satoshi/saving-satoshi/pull/194. We can probably add another line that says "Click next to continue" which should make the user at least want to look for a "next" button. But let me tag Christoph on this issue.

Vinayak, I tested paste functionality and it works great. I'm going to ask @afterburn to review the fix for command history. Lastly as I was testing spell check, I found a weird bug where the letters "fi" get smashed together if they're typed next to each other. I tried other letter combos but couldn't replicate. It's possible it could affect other letter combinations. 

I'll create another issue so we can track it properly but could you take a look to see if you can also include that in this PR?


Screenshot 2023-02-26 at 8 58 36 AM

**Comment by vinayaksh42** [comment]
the `fi` bug seems to be really weird. I tested it out on the [live website ](https://savingsatoshi.com/en/chapters/chapter-1/genesis-2) and the same behavior occurs. I think it might be due to the font style. Found [this](https://github.com/thespacedojo/crater-nova/issues/6) on the internet about it.

**Comment by ecurrencyhodler** [comment]
Based on that convo, it sounds like there are two fixes:

1. disable ligatures-> font-feature-settings: "liga" 0;
2. add slight letter spacing

I'm feeling like the first option might be best. WDYT?

**Comment by vinayaksh42** [comment]
> Based on that convo, it sounds like there are two fixes:
> 
> 1. disable ligatures-> font-feature-settings: "liga" 0;
> 2. add slight letter spacing
> 
> I'm feeling like the first option might be best. WDYT?

yes, the first option seems to be the best one. I have implemented it.

**Comment by ecurrencyhodler** [comment]
Sick. Thanks for taking on https://github.com/saving-satoshi/saving-satoshi/issues/202 as well.

File: ui/lesson/Terminal.tsx [hunk 1]
```diff
@@ -21,27 +23,23 @@ export default function Terminal({ success, lines, next, onChange }) {
...
+                className={clsx({
+                  'react-terminal-answer text-green': line.type === 'answer',
+                  'react-terminal-output text-[var(--terminal-output)]':
+                    line.type === 'output',
+                  'react-terminal-previous-input text-white/80':
+                    line.type === 'input',
+                  'mt-2.5': index != 0,
+                })}
               >
                 <TerminalOutput>{`${line.value}`}</TerminalOutput>
```
Comment (afterburn) [inline ui/lesson/Terminal.tsx:39]: I noticed `TerminalOutput` component is a single line of jsx, think it makes sense to just put that code here instead of having a dedicated component for it.

Comment (afterburn) [inline ui/lesson/Terminal.tsx:39]: gh pr checkout 201

File: ui/lesson/Terminal.tsx [hunk 2]
```diff
@@ -21,27 +23,23 @@ export default function Terminal({ success, lines, next, onChange }) {
     >
       <div className="flex grow flex-col items-stretch text-white">
         <div className="flex grow">
-          <ReactTerminal
-            name="Saving Satoshi"
-            colorMode={ColorMode.Light}
-            onInput={onChange}
-          >
+          <TerminalInterface onInput={onChange}>
```
Comment (afterburn) [inline ui/lesson/Terminal.tsx:26]: I think there are a little too much Terminal-related components. I feel the logic that now resides in `TerminalInterface` could just be added to this component (`ui/lesson/Terminal.tsx`).

**Review by afterburn — CHANGES_REQUESTED** [review]
Hey @vinayaksh42, great initial setup for a better terminal! I requested some small changes, but lgtm once you resolve them.

**Comment by afterburn** [comment]
Actually there is another issue where if you lose focus, and then click on the input again you can end up in the following situation when pressing up/down arrow keys.

saving-satoshi-terminal-bug

**Review by benalleng — CHANGES_REQUESTED** [review]
The fix for the "liga" font feature doesn't seem to be present in the Input field specifically
Perhaps explicitly specifying the font-family in the Input would solve this.

Also with large single words like hex values there isn't any word break so there are long horizontal scrollbars added to the terminal

image

**Comment by gadabra** [comment]
If `react-terminal-ui` package is not being used, you can remove it from the project.

**Comment by afterburn** [comment]
> If `react-terminal-ui` package is not being used, you can remove it from the project.

I think there are a couple other packages we can also remove, feel free to address those in this PR as well @vinayaksh42

**Comment by afterburn** [comment]
@vinayaksh42 I think the plan for the caret is to just use the normal one so maybe you can also tackle that in this PR.

**Comment by vinayaksh42** [comment]
I have removed `react-terminal-ui`, `date-fns`, and `react-individual-character-input-boxes` as they are not being used anymore. I have also added the `TerminalOutput` and `TerminalInterface` to the `Terminal` Component.

**Comment by vinayaksh42** [comment]
I have fixed the following issues:
- Lose focus upon challenge completion.
- the state of the challenge remains as completed upon getting the correct answer.

**Comment by vinayaksh42** [comment]
> Actually there is another issue where if you lose focus, and then click on the input again you can end up in the following situation when pressing up/down arrow keys.
> 
> saving-satoshi-terminal-bug

@afterburn I am unable to reproduce this bug, can you tell me about the browser you are using?

**Comment by ecurrencyhodler** [comment]
Amazing. 

- Confirmed that losing focus resolves https://github.com/saving-satoshi/saving-satoshi/issues/207.
- Confirmed that the state of the challenge remains as completed upon getting the correct answer resolves https://github.com/saving-satoshi/saving-satoshi/issues/205
- Confirmed link works and points to correct article.
IMG_1526

**Comment by ecurrencyhodler** [comment]
@vinayaksh42 I can confirm kevin's bug. If I click anywhere inside the console outside of the line where the carrot rests and start typing, nothing is entered. This occurs in chrome, firefox, and safari.

Also the carrot disappears on safari and firefox but is preserved in Chrome when I click outside the line. 

In Safari, the screen even scrolls when I press up or down.

This is pretty difficult to screen capture. If you can't reproduce I can hop on a call to show you.

**Comment by ecurrencyhodler** [comment]
Okay the bug I found is different. Vinayak is going to address it in this PR.

@afterburn I am also unable to reproduce the error. Vinayak and I hopped on the call to go through it together in Safari/firefox/chrome.

**Comment by afterburn** [comment]
Okay I installed another version of Chrome and the bug would not occur so it might be some weird setting or even an extension that causing the bug I reported. Feel free to ignore it.

**Review by benalleng — APPROVED** [review]
tACK for  issues #145, #187, #165, #202, #205, and #207
> 1. terminal interface height not spanning over the entire div

This bug has also been resolved

**Comment by ecurrencyhodler** [comment]
@afterburn looks like vinayak addressed your requests. Would you mind doing a review then we can merge?

Thanks Ben for the tACK.

**Review by afterburn — APPROVED** [review]
